# Generated by Django 3.0.3 on 2020-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200301_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=120, null=True, verbose_name='Kategori'),
        ),
    ]
