# Generated by Django 3.0.3 on 2020-03-08 17:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ürün Detayı'),
        ),
    ]
