# Generated by Django 3.0.3 on 2020-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200312_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='category',
            field=models.CharField(max_length=120, null=True, verbose_name='Kategori'),
        ),
    ]
